global:
  scrape_interval:  10s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'ob-system-monitor'

scrape_configs:
  - job_name: cadvisor
    static_configs:
      - targets:  ['190.190.20.12:8080']

  - job_name: 'kong_gateway'
    # scheme: https
    # tls_config:
    #   insecure_skip_verify: true
    static_configs:
      - targets: ['host.docker.internal:8001']
    
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['host.docker.internal:9100']

  - job_name: telegraf
    static_configs:
      - targets:  ['host.docker.internal:9273']
