global:
  scrape_interval:  5s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'ob-system-monitor'

scrape_configs:
  - job_name: 'kong_gateway'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['192.168.226.146:8444']

  - job_name: cadvisor
    static_configs:
      - targets:  ['190.190.20.12 .:8080']

  - job_name: telegraf
    static_configs:
      - targets:  ['192.168.226.146:9273']
