global:
  scrape_interval:  10s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'ob-system-monitor'

scrape_configs:
  - job_name: cadvisor
    static_configs:
      - targets:  ['190.190.20.12:8080']

  - job_name: 'kong_gateway'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['host.docker.internal:8444']
    
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['host.docker.internal:9100']

  - job_name: telegraf
    static_configs:
      - targets:  ['host.docker.internal:9273']

  - job_name: cbs-gateway
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets:  ['host.docker.internal:6060']
        labels:
          application: "cbs_gateway_service"
    # basic_auth:
    #   username: ob
    #   password: ob123

  - job_name: customer-onboarding-service
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets:  ['host.docker.internal:6161']
        labels:
          application: "customer_onboarding_service"
