global:
  scrape_interval:     1s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'kong_gateway'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['10.10.25.93:8444']

  - job_name: cadvisor
    static_configs:
      - targets:  ['190.190.20.11:8080']
